services:
  - type: web
    name: snipevision
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PORT
        value: 8501
      - key: SOLANA_WALLET_ADDRESS
        sync: false
      - key: HELIUS_API_KEY
        sync: false
      - key: LEMON_CHECKOUT_URL
        sync: false
      - key: LEMON_API_KEY
        sync: false
      - key: LEMON_VARIANT_ID
        sync: false

